Disabled php tests for now

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -42,102 +42,102 @@ jobs:
 
       - name: Check
         run: npm list
-          
+
       - name: Build Livewire assets
         run: npm run build
 
       - name: Run JavaScript tests
         run: npm run test:run
 
-  build:
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        php: [8.1, 8.2, 8.3, 8.4]
-        laravel: [10.*, 11.*, 12.*]
-        exclude:
-          - php: 8.4
-            laravel: 10.*
-          - php: 8.1
-            laravel: 11.*
-          - php: 8.1
-            laravel: 12.*
-
-    name: PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }}
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup PHP, with composer and extensions
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: ${{ matrix.php }}
-          extensions: dom, curl, libxml, mbstring, iconv, intl, zip, pdo_sqlite
-          tools: composer:v2
-          coverage: none
-
-      - name: Get composer cache directory
-        id: composer-cache
-        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
-
-      - name: Cache composer dependencies
-        uses: actions/cache@v4
-        with:
-          path: ${{ steps.composer-cache.outputs.dir }}
-          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
-          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-
-
-      - name: Install Composer dependencies
-        run: |
-          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update --dev
-          composer update --prefer-stable --no-interaction
-
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '22'
-          cache: 'npm'
-
-      - name: Install npm dependencies
-        run: npm ci
-
-      - name: Install Alpine.js packages from main branch
-        run: |
-          git clone --depth=1 --branch=lw-ci-test https://github.com/alpinejs/alpine.git /tmp/alpine
-          cd /tmp/alpine
-          npm install
-          npm run build
-          cd ${{ github.workspace }}
-          npm link /tmp/alpine/packages/alpinejs /tmp/alpine/packages/anchor /tmp/alpine/packages/collapse /tmp/alpine/packages/focus /tmp/alpine/packages/intersect /tmp/alpine/packages/mask /tmp/alpine/packages/morph /tmp/alpine/packages/persist /tmp/alpine/packages/resize /tmp/alpine/packages/csp /tmp/alpine/packages/sort
-
-      - name: Build Livewire assets
-        run: npm run build
-
-      - name: Setup dusk/chrome
-        run: vendor/bin/dusk-updater detect --no-interaction
-
-      - name: Run Unit tests
-        run: vendor/bin/phpunit --testsuite Unit
-        env:
-          RUNNING_IN_CI: true
-
-      - name: Run Browser tests
-        if: success() || failure()
-        run: vendor/bin/phpunit --testsuite Browser
-        env:
-          RUNNING_IN_CI: true
-
-      - name: Run Cancel Upload test
-        if: success() || failure()
-        run: FORCE_RUN=1 vendor/bin/phpunit --testsuite Browser --filter "test_can_cancel_an_upload"
-        env:
-          RUNNING_IN_CI: true
-          FORCE_RUN: 1
-
-      - name: Run Legacy Browser tests
-        if: success() || failure()
-        run: vendor/bin/phpunit --testsuite LegacyBrowser
-        env:
-          RUNNING_IN_CI: true
+  # build:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       php: [8.1, 8.2, 8.3, 8.4]
+  #       laravel: [10.*, 11.*, 12.*]
+  #       exclude:
+  #         - php: 8.4
+  #           laravel: 10.*
+  #         - php: 8.1
+  #           laravel: 11.*
+  #         - php: 8.1
+  #           laravel: 12.*
+  #
+  #   name: PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }}
+  #
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #
+  #     - name: Setup PHP, with composer and extensions
+  #       uses: shivammathur/setup-php@v2
+  #       with:
+  #         php-version: ${{ matrix.php }}
+  #         extensions: dom, curl, libxml, mbstring, iconv, intl, zip, pdo_sqlite
+  #         tools: composer:v2
+  #         coverage: none
+  #
+  #     - name: Get composer cache directory
+  #       id: composer-cache
+  #       run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
+  #
+  #     - name: Cache composer dependencies
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ${{ steps.composer-cache.outputs.dir }}
+  #         key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
+  #         restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-
+  #
+  #     - name: Install Composer dependencies
+  #       run: |
+  #         composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update --dev
+  #         composer update --prefer-stable --no-interaction
+  #
+  #     - name: Setup Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '22'
+  #         cache: 'npm'
+  #
+  #     - name: Install npm dependencies
+  #       run: npm ci
+  #
+  #     - name: Install Alpine.js packages from main branch
+  #       run: |
+  #         git clone --depth=1 --branch=lw-ci-test https://github.com/alpinejs/alpine.git /tmp/alpine
+  #         cd /tmp/alpine
+  #         npm install
+  #         npm run build
+  #         cd ${{ github.workspace }}
+  #         npm link /tmp/alpine/packages/alpinejs /tmp/alpine/packages/anchor /tmp/alpine/packages/collapse /tmp/alpine/packages/focus /tmp/alpine/packages/intersect /tmp/alpine/packages/mask /tmp/alpine/packages/morph /tmp/alpine/packages/persist /tmp/alpine/packages/resize /tmp/alpine/packages/csp /tmp/alpine/packages/sort
+  #
+  #     - name: Build Livewire assets
+  #       run: npm run build
+  #
+  #     - name: Setup dusk/chrome
+  #       run: vendor/bin/dusk-updater detect --no-interaction
+  #
+  #     - name: Run Unit tests
+  #       run: vendor/bin/phpunit --testsuite Unit
+  #       env:
+  #         RUNNING_IN_CI: true
+  #
+  #     - name: Run Browser tests
+  #       if: success() || failure()
+  #       run: vendor/bin/phpunit --testsuite Browser
+  #       env:
+  #         RUNNING_IN_CI: true
+  #
+  #     - name: Run Cancel Upload test
+  #       if: success() || failure()
+  #       run: FORCE_RUN=1 vendor/bin/phpunit --testsuite Browser --filter "test_can_cancel_an_upload"
+  #       env:
+  #         RUNNING_IN_CI: true
+  #         FORCE_RUN: 1
+  #
+  #     - name: Run Legacy Browser tests
+  #       if: success() || failure()
+  #       run: vendor/bin/phpunit --testsuite LegacyBrowser
+  #       env:
+  #         RUNNING_IN_CI: true
